import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// docs/ 内のファイルを sidebar_position 順に自動列挙する。
const sidebars: SidebarsConfig = {
  manualSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
